### PR TITLE
Escape attachments filenames so they can be safely saved

### LINKED ISSUE #378: Attachment saving and special characters in filenames
When saving attachments, sup should replace special characters when suggesting a filename to save the attachment to.

I just got an attachment with a name like "foo/2.pdf". sup suggests saving it to /home/fxkr/foo/2.pdf (and fails to save it, of course, if /home/fxkr/foo isn't a directory).

I haven't tested the "Save All" feature, but I hope nothing bad happens when there's an attachment called "../../../../../../../home/fxkr/.bashrc" ;-)

### PR DESCRIPTION
**Pull request by rakoo**
Fixes #378. Unfortunately I don't know how to unit-test it.

### CODE REVIEW

**Comment by gauteh** [comment]
Test: Perhaps a test with Pathname.realpath and if parent is the target directory or not. Then test for a bunch of examples.

**Comment by gauteh** [comment]
For reference: https://github.com/sup-heliotrope/sup/wiki/Security-%23SBU1

**Comment by rakoo** [comment]
Added a test: we verify that the `safe_filename` can't be interpreted into a path, it's a pure "basename"

**Comment by gauteh** [comment]
Looks good to me. Please feel free to merge (as well as the other requests you
think are ready as well), I don't have the chance at the moment.

Excerpts from Matthieu Rakotojaona's message of January 15, 2015 21:37:
> Added a test: we verify that the `safe_filename` can't be interpreted into a path, it's a pure "basename"
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sup-heliotrope/sup/pull/379#issuecomment-70157139
=

**Pull request merged**
