### PR TITLE
Fixed issue #374 - gave possibility to add sources, which names contain spaces

### LINKED ISSUE #374: Cannot add sources with spaces
```
tyrion@acerone:~/.sup$ sup-add "maildir:/home/tyrion/.Mail/account/Sent Items"                                                                                            
[2015-01-08 00:24:09 +0100] Flushing Xapian updates to disk. This may take a while...
/home/tyrion/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:176:in `split': bad URI(is not URI?): maildir:/home/tyrion/.Mail/account/Sent Items (URI::InvalidURIError)
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:1232:in `URI'
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sup-0.20.0/bin/sup-add:98:in `block in <top (required)>'
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sup-0.20.0/bin/sup-add:90:in `each'
        from /home/tyrion/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sup-0.20.0/bin/sup-add:90:in `<top (required)>'
        from /home/tyrion/.rbenv/versions/2.1.3/bin/sup-add:23:in `load'
        from /home/tyrion/.rbenv/versions/2.1.3/bin/sup-add:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by ty221**
Closed #374 

ping @eMBee

### CODE REVIEW

**Comment by rakoo** [comment]
I'd rather we rely on [stdlib](http://ruby-doc.org/stdlib-2.0/libdoc/uri/rdoc/URI/Escape.html), something like that:

```ruby
parsed_uri = URI(URI.escape(uri))
```

**Comment by ty221** [comment]
@rakoo Can you tell @eMBee is now everything ok with this PR??

**Comment by rakoo** [comment]
LGTM, now I'd just like it to be clean (yeah I'm picky :smiley: ): the diff shows useless spaces before and after the line. Also, since the change is small I'd rather see a single commit. @eMBee could you please merge those commits into a single one ?

**Comment by avtobiff** [comment]
@ty221 please also write good commit messages. Instead of "Fixed issue
374" state explicitly what is done.

Have a look at

    http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

Don't be afraid to write an essay! The history is the most important
communication with other developers (including your future self), so it
should really explain why a change is introduced.

I suggest that you do an interactive rebase and squash the commits and
then write something like:

    Replaced unsafe HTML characters with HTML entities

    <Possible motivation for why they are unsafe and thus replaced.
    (Maybe not really that important in this case.)>

    Closes: #374

**Comment by eMBee** [comment]
code-in task closed http://www.google-melange.com/gci/task/view/google/gci2014/5790761748529152 in #383

**Pull request closed without merging**
