### PR TITLE
Merge develop in use-mail

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
Easier to test what works and what doesn't.

### CODE REVIEW

**Comment by gauteh** [comment]
I think there is a bit of a mess surrounding the supsingleton stuff (#279), could you check that it matches `develop` ?

**Comment by gauteh** [comment]
Nevermind, the commits are not diverging, but sequential... SupSingleton stuff should be ok

**Comment by gauteh** [comment]
I get the following error when running rake test on ruby 2.1.1:
```
/home/gaute/.rvm/rubies/ruby-2.1.1/bin/ruby -I"lib:test" -I"/home/gaute/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib" "/home/gaute/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/integration/test_label_service.rb" "test/integration/test_maildir.rb" "test/integration/test_mbox.rb" "test/test_crypto.rb" "test/test_header_parsing.rb" "test/test_helper.rb" "test/test_message.rb" "test/test_messages_dir.rb" "test/test_yaml_migration.rb" "test/test_yaml_regressions.rb" "test/unit/service/test_label_service.rb" "test/unit/test_contact.rb" "test/unit/test_horizontal_selector.rb" "test/unit/test_locale_fiddler.rb" "test/unit/test_person.rb" "test/unit/util/test_query.rb" "test/unit/util/test_string.rb" "test/unit/util/test_uri.rb" 
[2015-04-26 15:42:21 +0200] using character set encoding "UTF-8"
[2015-04-26 15:42:22 +0200] WARNING: MiniTest::Unit::TestCase is now Minitest::Test. From /home/gaute/dev/mail/sup/sup.git/test/unit/test_locale_fiddler.rb:4:in `<top (required)>'
Some YAML tests are skipped on Ruby 2.1.0 and newer.
Run options: --seed 35477

# Running:

...[2015-04-26 15:42:22 +0200] WARNING: found invalid date in potential mbox split line, not splitting: "From sea to shining sea\n"
[2015-04-26 15:42:22 +0200] WARNING: found invalid date in potential mbox split line, not splitting: "From bob@bob.com I get only spam.\n"
..................EE..EE[2015-04-26 15:42:22 +0200] WARNING: content_type application/octet-stream; name=hacking is not safe, changed to application/octet-stream
[2015-04-26 15:42:22 +0200] WARNING: content_type text/plain; name=manifest.txt is not safe, changed to application/octet-stream
..[2015-04-26 15:42:22 +0200] WARNING: content_type text/x-yaml; name="sup/.travis.yml" is not safe, changed to application/octet-stream
.........S..[2015-04-26 15:42:22 +0200] Using fake id (newly created or existing):  for message located at: #<Redwood::Location:0x00000004e6a650 @source=#<Redwood::DummySource:0x00000004e6a768 @uri="sup-test://test_messages", @usual=true, @archived=false, @id=nil, @poll_lock=#<Monitor:0x00000004e6a718 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000004e6a6c8>>, @messages=["From: foo@example.org\nMIME-Version: 1.0\nContent-type: multipart/report; boundary=\"======11647==82899======\"; report-type=\"spam-notification\"\nSubject: Important\n\nThis is a multi-part message in MIME format...\n\n--======11647==82899======\nContent-Type: text/plain; charset=\"ISO-8859-1\"\nContent-Disposition: inline\nContent-Transfer-Encoding: quoted-printable\n\ntest\n\n--======11647==82899======\nContent-Type: message/rfc822\nContent-Disposition: attachment\nContent-Transfer-Encoding: binary\n\n\n--======11647==82899======--\n\n"]>, @info=0>.
[2015-04-26 15:42:22 +0200] WARNING: Invalid date for message 1430055742-defaulted-d90deb00b39b33435b1f2b345bb5e40f@sup-faked, using 'now' or previously fake 'now'.
[2015-04-26 15:42:22 +0200] RFC822 messages not implemented, skipping.
.[2015-04-26 15:42:22 +0200] Using fake id (newly created or existing):  for message located at: #<Redwood::Location:0x00000004e19c78 @source=#<Redwood::DummySource:0x00000004e19d68 @uri="sup-test://test_messages", @usual=true, @archived=false, @id=nil, @poll_lock=#<Monitor:0x00000004e19d18 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000004e19cc8>>, @messages=["From: foo@example.org\nMIME-Version: 1.0\nSubject: Content-Transfer-Encoding:-bug in sup\nContent-Type: message/rfc822\nContent-Transfer-Encoding: nosuchcontenttransferencoding\n\nfoo\n\n"]>, @info=0>.
[2015-04-26 15:42:22 +0200] WARNING: Invalid date for message 1430055742-defaulted-e26930c0ff617068cab17e1879ce1ecd@sup-faked, using 'now' or previously fake 'now'.
[2015-04-26 15:42:22 +0200] WARNING: problem reading message 1430055742-defaulted-e26930c0ff617068cab17e1879ce1ecd@sup-faked
[2015-04-26 15:42:22 +0200] could not load message: #<Redwood::Location:0x00000004e19c78 @source=#<Redwood::DummySource:0x00000004e19d68 @uri="sup-test://test_messages", @usual=true, @archived=false, @id=nil, @poll_lock=#<Monitor:0x00000004e19d18 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000004e19cc8>>, @messages=["From: foo@example.org\nMIME-Version: 1.0\nSubject: Content-Transfer-Encoding:-bug in sup\nContent-Type: message/rfc822\nContent-Transfer-Encoding: nosuchcontenttransferencoding\n\nfoo\n\n"]>, @info=0>, exception: #<Mail::UnknownEncodingType: Don't know how to decode nosuchcontenttransferencoding, please call #encoded and decode it yourself.>
.[2015-04-26 15:42:22 +0200] Using fake id (newly created or existing):  for message located at: #<Redwood::Location:0x00000004dfb2f0 @source=#<Redwood::DummySource:0x00000004dfb3e0 @uri="sup-test://test_messages", @usual=true, @archived=false, @id=nil, @poll_lock=#<Monitor:0x00000004dfb390 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000004dfb340>>, @messages=["From: foo@aol.com\nTo: foo@test.com\nSubject: Encoding bug\nContent-Type: text/plain; charset=\"iso-8859-1\"\nContent-Transfer-Encoding: quoted-printable\n\nThis is =91 a test: the first line seems to disappear from the mail body but is\nstill visible in the thread view.\n\n"]>, @info=0>.
[2015-04-26 15:42:22 +0200] WARNING: Invalid date for message 1430055742-defaulted-62108988b8473f2a8edcb65e73170961@sup-faked, using 'now' or previously fake 'now'.
.[2015-04-26 15:42:22 +0200] WARNING: No crypto set up, crypto will not be tested. Reason: The crypto code needs to be ported to use Mail not RMail
.[2015-04-26 15:42:22 +0200] WARNING: No crypto set up, crypto will not be tested. Reason: The crypto code needs to be ported to use Mail not RMail
.[2015-04-26 15:42:22 +0200] WARNING: No crypto set up, crypto will not be tested. Reason: The crypto code needs to be ported to use Mail not RMail
.[2015-04-26 15:42:22 +0200] WARNING: No crypto set up, crypto will not be tested. Reason: The crypto code needs to be ported to use Mail not RMail
.[2015-04-26 15:42:22 +0200] WARNING: No crypto set up, crypto will not be tested. Reason: The crypto code needs to be ported to use Mail not RMail
.[2015-04-26 15:42:22 +0200] WARNING: No crypto set up, crypto will not be tested. Reason: The crypto code needs to be ported to use Mail not RMail
..

Finished in 0.602437s, 84.6562 runs/s, 199.1909 assertions/s.

  1) Error:
TestMbox#test_can_index_a_mbox_directory:
RuntimeError: wrong id called on {"uri"=>"maildirroot:/home/gaute/.mail/gaute.vetsj.com/", "usual"=>true, "archived"=>false, "id"=>1, "labels"=>[], "sync_back"=>true, "confirm_enable_experimental"=>true, "maildir_creation_allowed"=>true, "inbox_folder"=>"inbox", "sent_folder"=>"sent", "drafts_folder"=>"drafts", "spam_folder"=>"spam", "trash_folder"=>"trash", "archive_folder"=>"archive"}
    /home/gaute/dev/mail/sup/sup.git/lib/sup.rb:21:in `id'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `block (2 levels) in load_sources'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `map'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `block in load_sources'
    /home/gaute/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:228:in `load_sources'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/util.rb:640:in `method_missing'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/index.rb:102:in `load'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/util.rb:640:in `method_missing'
    /home/gaute/dev/mail/sup/sup.git/test/integration/test_mbox.rb:35:in `start_sup_and_add_source'
    /home/gaute/dev/mail/sup/sup.git/test/integration/test_mbox.rb:46:in `test_can_index_a_mbox_directory'


  2) Error:
TestMbox#test_can_index_a_mbox_directory_with_special_characters:
RuntimeError: wrong id called on {"uri"=>"maildirroot:/home/gaute/.mail/gaute.vetsj.com/", "usual"=>true, "archived"=>false, "id"=>1, "labels"=>[], "sync_back"=>true, "confirm_enable_experimental"=>true, "maildir_creation_allowed"=>true, "inbox_folder"=>"inbox", "sent_folder"=>"sent", "drafts_folder"=>"drafts", "spam_folder"=>"spam", "trash_folder"=>"trash", "archive_folder"=>"archive"}
    /home/gaute/dev/mail/sup/sup.git/lib/sup.rb:21:in `id'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `block (2 levels) in load_sources'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `map'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `block in load_sources'
    /home/gaute/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:228:in `load_sources'
    (eval):1:in `load_sources'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/index.rb:102:in `load'
    (eval):1:in `load'
    /home/gaute/dev/mail/sup/sup.git/test/integration/test_mbox.rb:35:in `start_sup_and_add_source'
    /home/gaute/dev/mail/sup/sup.git/test/integration/test_mbox.rb:59:in `test_can_index_a_mbox_directory_with_special_characters'


  3) Error:
TestMaildir#test_can_index_a_maildir_directory:
RuntimeError: wrong id called on {"uri"=>"maildirroot:/home/gaute/.mail/gaute.vetsj.com/", "usual"=>true, "archived"=>false, "id"=>1, "labels"=>[], "sync_back"=>true, "confirm_enable_experimental"=>true, "maildir_creation_allowed"=>true, "inbox_folder"=>"inbox", "sent_folder"=>"sent", "drafts_folder"=>"drafts", "spam_folder"=>"spam", "trash_folder"=>"trash", "archive_folder"=>"archive"}
    /home/gaute/dev/mail/sup/sup.git/lib/sup.rb:21:in `id'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `block (2 levels) in load_sources'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `map'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `block in load_sources'
    /home/gaute/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:228:in `load_sources'
    (eval):1:in `load_sources'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/index.rb:102:in `load'
    (eval):1:in `load'
    /home/gaute/dev/mail/sup/sup.git/test/integration/test_maildir.rb:40:in `start_sup_and_add_source'
    /home/gaute/dev/mail/sup/sup.git/test/integration/test_maildir.rb:52:in `test_can_index_a_maildir_directory'


  4) Error:
TestMaildir#test_can_index_a_maildir_directory_with_special_characters:
RuntimeError: wrong id called on {"uri"=>"maildirroot:/home/gaute/.mail/gaute.vetsj.com/", "usual"=>true, "archived"=>false, "id"=>1, "labels"=>[], "sync_back"=>true, "confirm_enable_experimental"=>true, "maildir_creation_allowed"=>true, "inbox_folder"=>"inbox", "sent_folder"=>"sent", "drafts_folder"=>"drafts", "spam_folder"=>"spam", "trash_folder"=>"trash", "archive_folder"=>"archive"}
    /home/gaute/dev/mail/sup/sup.git/lib/sup.rb:21:in `id'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `block (2 levels) in load_sources'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `map'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:229:in `block in load_sources'
    /home/gaute/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/source.rb:228:in `load_sources'
    (eval):1:in `load_sources'
    /home/gaute/dev/mail/sup/sup.git/lib/sup/index.rb:102:in `load'
    (eval):1:in `load'
    /home/gaute/dev/mail/sup/sup.git/test/integration/test_maildir.rb:40:in `start_sup_and_add_source'
    /home/gaute/dev/mail/sup/sup.git/test/integration/test_maildir.rb:65:in `test_can_index_a_maildir_directory_with_special_characters'

51 runs, 120 assertions, 0 failures, 4 errors, 1 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/gaute/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib" "/home/gaute/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/integration/test_label_service.rb" "test/integration/test_maildir.rb" "test/integration/test_mbox.rb" "test/test_crypto.rb" "test/test_header_parsing.rb" "test/test_helper.rb" "test/test_message.rb" "test/test_messages_dir.rb" "test/test_yaml_migration.rb" "test/test_yaml_regressions.rb" "test/unit/service/test_label_service.rb" "test/unit/test_contact.rb" "test/unit/test_horizontal_selector.rb" "test/unit/test_locale_fiddler.rb" "test/unit/test_person.rb" "test/unit/util/test_query.rb" "test/unit/util/test_string.rb" "test/unit/util/test_uri.rb" ]
/home/gaute/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/home/gaute/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by gauteh** [comment]
Which also happens on `develop`, seems like the test is using .sup/config.yml.. that's bad..

**Comment by ZJvandeWeg** [comment]
@gauteh 
I was sloppy. Will fix this in the comming week.

**Comment by gauteh** [comment]
@ZJvandeWeg: do you know which commits introduced the issues with using ~/.sup? Seems it is not happening on this machine, can you reproduce it?

**Pull request closed without merging**
