### PR TITLE
Re-port support for syncing back labels to/from X-Keywords 

### PR DESCRIPTION
**Pull request by cro**
I wrote this support a long time ago and it bit rotted against current sup releases.  I've ported the patches and think this is now actually a simpler approach.

Note that I'm not sure that this will work against the currently released offlineimap version.  I know that my fork of offlineimap will work with it (https://github.com/cro/offlineimap) and I have a PR into the offlineimap project to fix an issue I found (they may very well fix it a different way).

### CODE REVIEW

**Comment by Procrat** [comment]
Is there any progress on this? I would love this feature.

**Comment by cro** [comment]
I'm no longer using Sup, so I'm not working on this feature anymore.

--cro

**Comment by gauteh** [comment]
Closing.

**Comment by Eising** [comment]
I've just carbon copied this code in to a branch of my own, and started testing it. If it runs well, I'll add a new pull request for it and maintain it myself. I need this feature, so I'm willing to do it myself.

**Pull request closed without merging**
