### PR TITLE
fix attachment escaping

### LINKED ISSUE #505: Escaping spaces in saved attachment
When asking for the name when saving an attachment to disk, sup automatically escapes spaces. However, the "file saving part" of sup seems to have no need for the escapes.

Reproduction:
- receive a mail with an attachment called `foo bar.pdf`
- focus the attachment and hit `s`
- sup asks `Save attachment to file or directory: /my/default/dir/foo\ bar.pdf`
- I hit enter
- sup says `Successfully wrote /my/default/dir/foo\ bar.pdf.`
- The file `/my/default/dir/foo\ bar.pdf` is created, while one would expect `/my/default/dir/foo bar.pdf`

How to fix this:
- Either interpret escaping in the filename;
- or, which would actually make sense, don't automatically escape spaces when suggesting the filename.

Additional information:
- sup v0.22.1
- ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
- system: Linux, 4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by ninewise**
Closes #505

### CODE REVIEW

**Comment by gauteh** [comment]
Make sure this doesn't open for this kind of attack: https://github.com/sup-heliotrope/sup/wiki/Security-%23SBU1 - it does not immediately seem like a problem.

**Comment by NoctuaNivalis** [comment]
I was looking around a bit, and apparently I reversed some earlier commit to allow saving attachments with slashes. Fixed that.

**Comment by mklinik** [comment]
`chunk.safe_filename` is the shell-escaped filename where slashes are replaced by underscores. You only need to shell-escape a filename if you pass it to a shell like command interpreter, as in `chunk.view_default`. There, the filename is eventually passed to `system`. But when the filename is used directly to open the file, we don't need to escape it.
I think it is a bug to use `safe_filename` for saving the attachment. Using just `chunk.filename` should be fine.

I think @NoctuaNivalis' commits can safely be merged.

**Comment by danc86** [comment]
This fix is good, but for some reason when I restart the Travis build it insists on using an old, broken build config instead of merging with `develop` (where the build is now fixed). I'm not sure what's going on there.

So I've squashed these two commits and re-posted them with a clearer commit message in PR #558. I'm closing this PR in favour of the other one.

Thanks very much for your contribution!

**Comment by ninewise** [comment]
I didn't even remember this, but thank you for merging this into master.

**Pull request closed without merging**
