### PR TITLE
Refactor with/against Rubocop

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
In response to #402. I've implemented Rubocop for this project. 

Created this PR in case someone wants to help out?

### CODE REVIEW

**Comment by rakoo** [comment]
For reference, here's a list of all style errors found in [731.1](https://travis-ci.org/sup-heliotrope/sup/jobs/54260805):

```
lib/sup/crypto.rb:86:9: C: Style/AlignArray: Align the elements of an array literal if they span more than one line.
        'Install the gpgme gem in order to use signed and encrypted emails']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/message_chunks.rb:134:25: C: Style/AlignHash: Align the elements of a hash literal if they span more than one line.
                        :filename => lambda { write_to_disk },
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/crypto.rb:101:32: C: Style/AlignParameters: Align the parameters of a method call if they span more than one line.
                               {:operation => "sign", :options => {}}) || {}
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/message.rb:671:9: C: Style/AsciiComments: Use only ascii symbols in comments.
        # look for next nonblank line only when needed to avoid O(n²)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/maildir.rb:133:33: C: Style/BlockEndNewline: Expression at 133, 33 should be on its own line.
          |f| !File.directory? f}.map {
                                ^
lib/sup/maildir.rb:134:47: C: Style/BlockEndNewline: Expression at 134, 47 should be on its own line.
            |x| File.join(d,File.basename(x)) }.sort }
                                              ^
lib/sup/maildir.rb:134:54: C: Style/BlockEndNewline: Expression at 134, 54 should be on its own line.
            |x| File.join(d,File.basename(x)) }.sort }
                                                     ^
lib/sup/modes/thread_index_mode.rb:1002:60: C: Style/Blocks: Avoid using {...} for multi-line blocks.
      (t.labels - @hidden_labels).sort_by {|x| x.to_s}.map {
                                                           ^
lib/sup/crypto.rb:69:33: C: Style/BracesAroundHashParameters: Redundant curly braces around a hash parameter.
            GPGME.check_version({:protocol => GPGME::PROTOCOL_OpenPGP})
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/util.rb:330:12: C: Style/CharacterLiteral: Do not use the character literal - use string literal instead.
      when ?"
           ^^
lib/sup/index.rb:858:7: C: Style/ClassAndModuleChildren: Use nested module/class definitions instead of compact style.
class Xapian::Document
      ^^^^^^^^^^^^^^^^
lib/sup/undo.rb:14:5: C: Style/ClassVars: Replace class var @@actionlist with a class instance var.
    @@actionlist = []
    ^^^^^^^^^^^^
lib/sup/colormap.rb:29:3: C: Style/ClassVars: Replace class var @@instance with a class instance var.
  @@instance = nil
  ^^^^^^^^^^
lib/sup/mode.rb:6:3: C: Style/ClassVars: Replace class var @@keymaps with a class instance var.
  @@keymaps = {}
  ^^^^^^^^^
lib/sup/message_chunks.rb:110:5: C: Style/ClassVars: Replace class var @@view_tempfiles with a class instance var.
    @@view_tempfiles = []
    ^^^^^^^^^^^^^^^^
lib/sup/index.rb:210:7: C: Style/CommentAnnotation: Annotation keywords should be all upper case, followed by a colon and a space, then a note describing the problem.
    # TODO thread by subject
      ^^^^
lib/sup/person.rb:30:1: C: Style/CommentIndentation: Incorrect indentation detected (column 0 instead of 2).
#   alias :eql? :==
^^^^^^^^^^^^^^^^^^^
lib/sup/message_chunks.rb:100:1: C: Style/CommentIndentation: Incorrect indentation detected (column 0 instead of 4).
#' stupid ruby-mode
^^^^^^^^^^^^^^^^^^^
lib/sup.rb:282:1: C: Style/CommentIndentation: Incorrect indentation detected (column 0 instead of 8).
#' stupid ruby-mode
^^^^^^^^^^^^^^^^^^^
lib/sup/message_chunks.rb:121:25: C: Style/CommentIndentation: Incorrect indentation detected (column 24 instead of 6).
                        # mime-decode hook, or if it's plain text
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/util.rb:475:28: C: Style/CommentIndentation: Incorrect indentation detected (column 27 instead of 4).
                           # compat chars.
                           ^^^^^^^^^^^^^^^
lib/sup/modes/scroll_mode.rb:34:40: C: Style/CommentIndentation: Incorrect indentation detected (column 39 instead of 4).
                                       # how many lines do we keep?
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/modes/scroll_mode.rb:208:7: C: Style/CommentIndentation: Incorrect indentation detected (column 6 instead of 4).
      # return
      ^^^^^^^^
lib/sup/message.rb:524:9: C: Style/CommentIndentation: Incorrect indentation detected (column 8 instead of 7).
        ## try inline pgp signed
        ^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/sent.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class SentManager
^^^^^
lib/sup/util/locale_fiddler.rb:8:1: C: Style/Documentation: Missing top-level module documentation comment.
module LocaleFiddler
^^^^^^
lib/sup/util/ncurses.rb:123:98: C: Style/DotPosition: Place the . on the next line, together with the method name.
      [ :"[]=", :"<<", :replace, :insert, :prepend, :append, :concat, :force_encoding, :setbyte ].
                                                                                                 ^
lib/sup/sent.rb:50:3: C: Style/EmptyLineBetweenDefs: Use empty lines between defs.
  def uri; 'sup://sent' end
  ^^^
lib/sup/person.rb:81:1: C: Style/EmptyLinesAroundClassBody: Extra empty line detected at class body beginning.
lib/sup/person.rb:82:22: C: Style/MethodDefParentheses: Use def with parentheses when there are parameters.
    def full_address name, email
lib/sup/person.rb:136:1: C: Style/EmptyLinesAroundClassBody: Extra empty line detected at class body end.
lib/sup/poll.rb:88:1: C: Style/EmptyLinesAroundMethodBody: Extra empty line detected at method body end.
lib/sup/poll.rb:98:13: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
      debug "poll already in progress."
lib/sup/sent.rb:2:1: C: Style/EmptyLinesAroundModuleBody: Extra empty line detected at module body beginning.
lib/sup/sent.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class SentManager
lib/sup/sent.rb:57:1: C: Style/EmptyLinesAroundModuleBody: Extra empty line detected at module body end.
lib/sup/search.rb:4:1: C: Style/EmptyLinesAroundModuleBody: Extra empty line detected at module body beginning.
lib/sup/search.rb:5:1: C: Style/Documentation: Missing top-level class documentation comment.
lib/sup/person.rb:74:1: C: Style/EmptyLines: Extra blank line detected.
lib/sup/person.rb:77:48: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
    [name, email, email.split(/@/).first].join(" ")
lib/sup/util.rb:606:26: C: Style/FlipFlop: Avoid the use of flip flop operators.
    select { |l| true if l == startline .. l == endline }
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/sent.rb:44:40: C: Style/GlobalVars: Do not introduce global variables.
    super "mbox://" + @filename, true, $config[:archive_sent]
                                       ^^^^^^^
lib/sup/util/ncurses.rb:223:5: C: Style/GuardClause: Use a guard clause instead of wrapping the code inside a conditional expression.
    if not defined? Ncurses.get_wch
    ^^
lib/sup/search.rb:24:53: C: Style/HashSyntax: Use the new Ruby 1.9 hash syntax.
    @predefined_queries  = { 'All mail'.to_sym => { :qobj => Xapian::Query.new('Kmail'),
                                                    ^^^^^^^^
lib/sup/modes/thread_index_mode.rb:1001:5: C: Style/IndentArray: Indent the right bracket the same as the start of the line where the left bracket is.
    ] +
    ^
lib/sup/modes/thread_index_mode.rb:998:7: C: Style/IndentArray: Use 2 spaces for indentation in an array, relative to the start of the line where the left bracket is.
      [:size_widget_color, size_widget_text],
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/hook.rb:118:5: C: Style/IndentationConsistency: Inconsistent indentation detected.
    HookManager.descs.sort.each do |name, desc|
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/sent.rb:3:1: C: Style/IndentationWidth: Use 2 (not 0) spaces for indentation.
class SentManager

lib/sup/colormap.rb:193:7: C: Style/IndentationWidth: Use 2 (not -12) spaces for indentation.
      debug "loading user colors from #{Redwood::COLOR_FN}"
      ^^^^^^^^^^^^
lib/sup/modes/thread_view_mode.rb:905:9: C: Style/IndentationWidth: Use 2 (not -13) spaces for indentation.
        [star_color, "*"]
        ^^^^^^^^^^^^^
lib/sup/message.rb:133:7: C: Style/IndentationWidth: Use 2 (not -14) spaces for indentation.
      address = if header["list-post"] =~ /mailto:(.*?)[>\s$]/
      ^^^^^^^^^^^^^^
lib/sup/message.rb:525:7: C: Style/IndentationWidth: Use 2 (not 1) spaces for indentation.
      	chunks = inline_gpg_to_chunks m.body, $encoding, (m.charset || $encoding)
      ^
lib/sup/message.rb:94:7: C: Style/IndentationWidth: Use 2 (not -26) spaces for indentation.
      header["from"]
      ^^^^^^^^^^^^^^
lib/sup/hook.rb:113:1: C: Style/IndentationWidth: Use 2 (not -2) spaces for indentation.
puts <<EOS
^^
lib/sup/modes/file_browser_mode.rb:46:3: C: Style/IndentationWidth: Use 2 (not 3) spaces for indentation.
     name, f = @files[curpos - RESERVED_ROWS]
  ^^^
lib/sup/util.rb:35:3: C: Style/IndentationWidth: Use 2 (not 4) spaces for indentation.
      "host: %s\npid: %s\nppid: %s\ntime: %s\nuser: %s\npname: %s\n" %
  ^^^^
lib/sup/modes/thread_view_mode.rb:569:7: C: Style/IndentationWidth: Use 2 (not -5) spaces for indentation.
      message_left
      ^^^^^
lib/sup/person.rb:12:7: C: Style/IndentationWidth: Use 2 (not -6) spaces for indentation.
      name.fix_encoding!
      ^^^^^^
lib/sup/modes/edit_message_mode.rb:529:9: C: Style/IndentationWidth: Use 2 (not 6) spaces for indentation.
              warn "Sendmail hook was not successful"
        ^^^^^^
lib/sup/message.rb:649:9: C: Style/IndentationWidth: Use 2 (not -7) spaces for indentation.
        children = message_to_chunks(decryptedm, true)
        ^^^^^^^
lib/sup/message.rb:134:9: C: Style/IndentationWidth: Use 2 (not -8) spaces for indentation.
        $1
        ^^
lib/sup/util/ncurses.rb:263:9: C: Style/LeadingCommentSpace: Missing space after #.
        #c.is_a?(Fixnum) ? c : c.ord
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/sup/util.rb:306:25: C: Style/MethodCallParentheses: Do not use parentheses for method calls with no arguments.
    normalize_whitespace().split(/,\s*(?=(?:[^"]*"[^"]*")*(?![^"]*"))/)
                        ^
lib/sup/sent.rb:8:18: C: Style/MethodDefParentheses: Use def with parentheses when there are parameters.
  def initialize source_uri
                 ^^^^^^^^^^
lib/sup/modes/thread_index_mode.rb:517:7: C: Style/MultilineBlockChain: Avoid multi-line chains of blocks.
      end.each do |t|
      ^^^^^^^^
lib/sup/modes/thread_index_mode.rb:1003:13: C: Style/MultilineBlockLayout: Block argument expression is not on the same line as the block start.
            |label| [Colormap.sym_is_defined("label_#{label}_color".to_sym) || :label_color, "#{label} "]
            ^^^^^^^
lib/sup/modes/thread_view_mode.rb:772:7: C: Style/MultilineOperationIndentation: Align the operands of an expression in an assignment spanning multiple lines.
      .take_while{|d| d[0] == :text_color and d[1].strip != ""} # Only take up to the first "" alone on its line
      ^^^^^^^^^^^
lib/sup/util/ncurses.rb:124:7: C: Style/MultilineOperationIndentation: Use 2 (not 0) spaces for indenting an expression spanning multiple lines.
      select{ |m| public_method_defined?(m) }.
      ^^^^^^
lib/sup/buffer.rb:660:8: C: Style/MultilineOperationIndentation: Use 2 (not 1) spaces for indenting an expression spanning multiple lines.
       (@asking ? 1 : 0) +
       ^^^^^^^^^^^^^^^^^
lib/sup/message.rb:553:52: C: Style/NumericLiterals: Separate every 3 digits in the integer portion of a number with underscores(_).
          ["sup-attachment-#{Time.now.to_i}-#{rand 10000}", extension].join(".")
                                                   ^^^^^
lib/sup/modes/completion_mode.rb:24:13: C: Style/OneLineConditional: Favor the ternary operator (?:) over if/then/else/end constructs.
  def roll; if at_bottom? then jump_to_start else page_down end end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by rakoo** [comment]
Some comments on the rules I don't totally agree with:

- __Style/AndOr__: I actually like prose as defined in HACKING: use `||` and `&&` for tests, use `and` and `or` for control flow. But it seems it's against the good style both from GH and rubocop
- __Style/AsciiComments__: this contradicts the [Use UTF-8 everywhere](https://github.com/bbatsov/ruby-style-guide#utf-8) rule. I'm ok with UTF-8 comments
- __Style/EmptyLineBetweenDefs__: I'm ok with not having spaces between `def`s, particularly when they are single line
- __Style/HashSyntax__: GH says "use hash rockets", rubocop says "Use new syntax"... I'm ok with both (not at the same time of course)
- __Style/MethodDefParentheses__: I'm ok with not having parentheses when arguments are "simple"
- __Style/MultilineBlockChain__: What's the alternative ? Creating intermediate variables ? I'm not sure I like it
- __Style/SingleLineMethods__: I do like single line methods when they're simple

Thanks for starting this !

**Comment by ZJvandeWeg** [comment]
No problem! I agree with you on most things. Also, what happens if Rubocop changes policy later on, is sup then refactored again? 

When I opened #402 I didn't expect there to be over 5k violations. Im wondering if it wouldn't be a better approach to disable all rules and then incrementely enable rules?

**Comment by maxmeyer** [comment]
@ZJvandeWeg 

> over 5k violations

:smiley: Sorry for not mention that this is very likely to happen. But ....

>approach to disable all rules and then incrementely enable rules?

This is possible. I suggest to fix those violations incremental by:

1. Run rubocop with `--auto-gen-config`

  This will generate a configuration file which disables all violoations and modify all rubocop configuration values to "suppress" violations. To enable a "cop" just remove the entry from the file and the violation occures again.
  
  ```
  rubocop --auto-gen-config
  ```
  This will create a "todo" file.

2. Include "todo"-file in `.rubocop.yml`

  See the [man page](https://github.com/bbatsov/rubocop#automatically-generated-configuration) for more information about this.

  ```yaml
  inherit_from: .rubocop_todo.yml
  ```

3. Enable cop

   Remove an entry from the file.

4. Run rubocop

  If  `rubocop` provides an autocorrection for the violation use the following code snippet:

  ```bash
  rubocop --auto-correct
  ```
  This works quite good. I've never found, that this introduced a bug in my code.

5. Fix the violation

  If no autocorrection is available, you need to fix it by hand. If you disagree with a violation and don't want to disable it globally place `rubocop:disable` and `rubocop:enabl` around the code block.

  ```
  # rubocop:disable Style/MethodLength
  def my_method
    [...]
  end
  # rubocop:enable Style/MethodLength
```

6. Run test suite

  Just to make sure not bug was introduced by the refactoring, run the test suite

7. Commit change

  Add a commit for the change. This gives you a nice overview what was fixed by rubocop/you

8. Back to 3.

Cheers,
/mm

**Comment by maxmeyer** [comment]
:warning: I strongly recommend to use the `--auto-correct`-switch a lot. Otherwise it is a lot of work to fix violations, especially the whitespace ones.

**Comment by maxmeyer** [comment]
BTW: Nice to see `sup` is improving. :smile: I use it a lot.

**Comment by ZJvandeWeg** [comment]
@maxmeyer 
Thanks for the pointers. Picked some low hanging fruit just now, will continue later. Up untill now al test where passing at my local machine.

**Comment by maxmeyer** [comment]
Wow... Looks like you invest a large amount of time. :+1: :smile:

**Comment by gauteh** [comment]
Nice work, are you running this branch locally as well?

**Comment by ZJvandeWeg** [comment]
Not yet, still running the rmail branch (#397).
I've done about half of all the --auto-correct cases. After that it seems like a more suitable moment to do so.

**Comment by ZJvandeWeg** [comment]
I think ill stop at this point, as the rest requires major refactoring of the source instead of minor edits. 
Soon ill run this branch at home, combined with the rmail branch to detect any bugs.

**Comment by terotil** [comment]
@rakoo wrote
> Style/MultilineBlockChain: What's the alternative ? Creating intermediate variables ? I'm not sure I like it

In many cases I'd expect that extracting blocks as methods would clean the source in addition to getting rind of the style violations. That way you also get to give a name for the operation the piece of code does and thus ad semantics.

**Pull request closed without merging**
