### PR TITLE
Replace dl/import with Fiddle providing Ruby 2.2.0 support

### PR DESCRIPTION
**Pull request by timonv**
Luckily, Fiddle is well documented and easy to grasp.

Sup boots as normal and no errors/ weird chars.

image

### CODE REVIEW

**Comment by maxmeyer** [comment]
would be great to see this merge. 

BTW
This works fine as well: http://docs.ruby-lang.org/en/2.1.0/Fiddle/Importer.html

**Comment by timonv** [comment]
Huh, I could swear that part of the documentation wasn't there before. Must be my drinking problems.

**Comment by gauteh** [comment]
:+1:

**Comment by gauteh** [comment]
Would be great with a test for this one.

**Comment by timonv** [comment]
Sure! Any pointers? What about multi arch? I could use fiddle in a test to verify the locale has been set. Would that be enough?

**Comment by gauteh** [comment]
Yeah, that should be enough. Then we know that it works and on what
rubies it works on. We'll deal with multi-arch as the problems
arise, the test should test the code so that any problems are cought
in the test as well.


Excerpts from Timon Vonk's message of January 12, 2015 12:32:
> Sure! Any pointers? What about multi arch? I could use fiddle in a test to verify the locale has been set. Would that be enough?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sup-heliotrope/sup/pull/360#issuecomment-69557768
=

**Comment by timonv** [comment]
Added a chunk of code, WIP. Bit time occupied, working OS is still halfway there.

Couple things:

* I tried @maxmeyer's solution, but ran into a weird 'undefined method [] for NilClass' error on the extern line. This has my preference, it's easier and cleaner, at the end.
* Hacking with the fiddle calls, according to the man page, setlocale should return whatever changed when called, and you can call it with a null pointer to check. Sounds great, but it seg faults.
* Sorry for the naming puns, I have no idea why this works. Does anyone? Mildly curious.

Build probably fails, woops.

**Comment by gauteh** [comment]
Remember you can run `rake test` locally.

**Comment by timonv** [comment]
> Remember you can run rake test locally.

Ofcourse. If anyone has experience dealing with fiddle so I can solve this in a snap, that would be appreciated, hence the push. Otherwise I might have some more time later this weekend.

**Comment by maxmeyer** [comment]
Mmm, I've no experience with `fiddle` either. I'm running sup now with that code found below

```ruby
unless RbConfig::CONFIG['arch'] =~ /openbsd/
  require 'fiddle'
  require 'fiddle/import'

  module LibC
    extend Fiddle::Importer
    setlocale_lib = case RbConfig::CONFIG['arch']
      when /darwin/; "libc.dylib"
      when /cygwin/; "cygwin1.dll"
      when /freebsd/; "libc.so.7"
      else; "libc.so.6"
    end

    debug "dynamically loading setlocale() from #{setlocale_lib}"
    begin
      dlload setlocale_lib
      extern "void setlocale(int, const char *)"
      debug "setting locale..."
      LibC.setlocale(6, "")  # LC_ALL == 6
    rescue RuntimeError => e
      warn "cannot dlload setlocale(); ncurses wide character support probably broken."
      warn "dlload error was #{e.class}: #{e.message}"
    end
  end
end
```

**Comment by timonv** [comment]
Thanks @maxmeyer, getting it two work is not the problem, testing it proper (locale gets set to empty string), is. I have a hunch it's segfaulting because of the wrong type signature I used. We'll see.

**Comment by maxmeyer** [comment]
Ok. :-)

**Comment by timonv** [comment]
Pfft finally had some time :-) Added a very silly test. The second value seems to not always be the same. I have no idea why it would do that (to_s returns the value, not an address).  If someone has a better idea for tests, please, be my guest :)

You'd kinda expect any of the locale env vars to be changed, but nothing happens.

Tested on Archlinux, works fine.

**Comment by gauteh** [comment]
It seems this drops support for Ruby 1.9.

**Comment by timonv** [comment]
Ohhh

**Comment by timonv** [comment]
You alright with a ruby version check?

**Comment by timonv** [comment]
Also, is that needed? It's not exactly a python scenario. On a development machine there's no good reason not to update.

**Comment by gauteh** [comment]
I don't know if it is needed anymore, what rubies are e.g. debian running now?

**Comment by timonv** [comment]
I was just fiddling with a digital ocean ubuntu instance and it had both 1.9 and 2.0. Arguably, if you're using sup, you know what you're doing. Why not install the latest ruby? It's significantly faster anyway.

**Comment by gauteh** [comment]
I don't think so, many of the sup users are not ruby developers. But it might be time to drop 1.9 anyway, a quick survey on the mailing list should do the trick. Otherwise, do a version check, and we drop 1.9 later.

**Comment by ZJvandeWeg** [comment]
@timonv 
Might want to add ruby 2.2 for Travis aswell now.

**Comment by gauteh** [comment]
Excerpts from ZJvandeWeg's message of January 29, 2015 9:32:
> @timonv 
> Might want to add ruby 2.2 for Travis aswell now.

Good idea. Check out .travis.yml.


=

**Comment by timonv** [comment]
Fixed Time.parse not accepting an int anymore in ruby 2.2.0.

rr is unmaintained and no longer working with ruby 2.2.0. I have *no clue* whateverthefuck this particular test is trying to mock. Pointers greatly appreciated, should be possible to do this in just ruby as its just for one test anyway.

**Comment by timonv** [comment]
Truly stumped, but now it all seems to work. Wat.

**Comment by gauteh** [comment]
Yep. I guess it's time to drop 1.9.3, we don't have the resources to
maintain backward compatability for very long.

Will merge when people have had the chance to comment.

**Comment by maxmeyer** [comment]
See https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/ for EOL

**Comment by gauteh** [comment]
Excerpts from maxmeyer's message of February 4, 2015 13:46:
> See https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/ for EOL

Thanks, that settles it :)

**Pull request merged**
