### PR TITLE
Using terceiro's fork of rmail

### LINKED ISSUE #394: rmail being maintained again
I got in touch with the gem owners for rmail and permission to push new versions. I have added a bunch of patches that got accumulated in the Debian package for supporting newer Ruby versions, plus fixed to the test suite etc, and I am willing to maintain it going forward.

There is a 1.1.0 release uploaded to rubygems with those fixes, and I am now looking at the issues and pull requests from your `sup-rmail` fork. It would be nice if you could use that instead of a local fork.

See [terceiro/rmail](https://github.com/terceiro/rmail)

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
Potentially closes #394, will run this branch for the next period to see if something broke.

### CODE REVIEW

**Comment by gauteh** [comment]
You could try to re-index your entire message base, that should provide a
good first test. Using SUP_BASE you can set up a different .sup home
directory.

**Comment by gauteh** [comment]
Does this fix #205?

**Comment by ZJvandeWeg** [comment]
Will look into that this evening. 
I've setup a new folder with a copy of my Maildir, the indexing went fine. Though I might have a small inbox, +- 5k mail.
Will report later and do further testing, also regarding #205.

**Comment by ZJvandeWeg** [comment]
I've just looked at the issue, and the Regexp has not yet been changed in the new rmail. So https://github.com/sup-heliotrope/sup/issues/205#issuecomment-33314964 still happens. Im opening an issue right now.

**Comment by gauteh** [comment]
Note that the proposed fix in #205 probably is incorrect.

**Comment by ZJvandeWeg** [comment]
Been running this branch now for a month or so; so far no problems. Just reindexed my maildir again, works flawless.

**Comment by gauteh** [comment]
We should set up tests for the changes we did to rmail-sup so that we are sure that tcerio-rmail handles the previous issues, as I mentioned: the fix in #205 should not be implemented as it is, it probably does _not_ conform with standards. Mail standards are very hard to get right, which is a good reason for switching to the mail gem if possible. It seems to have a larger developer and user group, as well as being more modern (working better with recent rubies) and designed better than rmail.

**Comment by gauteh** [comment]
Also, it would be nice if the stuff we currently keep here: https://github.com/sup-heliotrope/sup/blob/develop/lib/sup/util.rb#L80 could be moved to rmail.

**Comment by gauteh** [comment]
As I also meniton in https://github.com/terceiro/rmail/issues/1 there is a bunch of tests that currently fail in #214 that would be nice to add to this PR, if they cannot be fixed atm, perhaps add them as expected failures.

**Comment by ZJvandeWeg** [comment]
Allright, wasn't aware of the desire to swap towards the mail gem over rmail.

**Comment by gauteh** [comment]
Yup, check out: #127. But, I don't remember exactly where I left off anymore - there are some issues and stuff that needs re-implementation. It would, in my opinion, be a major advancement though.

**Comment by ZJvandeWeg** [comment]
Will take a look into that when I've got the time then!

**Pull request merged**
