### PR TITLE
Add support for URI in signature to goto_uri

### PR DESCRIPTION
**Pull request by kalifg**
## Background
The `goto_uri` function works fine in the body of the message, but when attempting to use it on a URL in the signature I received the message `No URI found.`

## Solution
The code was considering only text marked in `:text_color`, while signatures use `:sig_color`.  I have modified the logic to include this as well.

### CODE REVIEW

**Comment by danc86** [comment]
Thanks for this patch, it looks good to me. If you could rebase this on the latest `develop` branch we should get a passing Travis build.

**Comment by IPv2** [comment]
@kalifg Alternatively: if you're no longer interested (e.g., not a sup user any longer) then I'm happy to rebase for you and raise a new PR, crediting you.

**Comment by IPv2** [comment]
Thanks @kalifg!

Looks good to me.

**Comment by kalifg** [comment]
You're welcome!  I haven't used it in a while, but with the new activity I'll be sure to give it another look.

**Pull request merged**
