### PR TITLE
Handle content-type-headers with spaces around parameter equal-sign

### PR DESCRIPTION
**Pull request by yzzyx**
For fixing bug 418

### CODE REVIEW

**Comment by gauteh** [comment]
Hm, this should probably be fixed in rmail ( @terceiro, what do you think?).

**Comment by gauteh** [comment]
By the way, is this behaviour allowed by the standard?

**Comment by terceiro** [comment]
rmail does not handle the header contents, so this probably has to be fixed in sup which was already doing that anyway. the RFCs seems to omit whitespace when talking about the Content-Type syntax, so if there are user agents out there using spaces I would say it makes sense to support it.

**Comment by yzzyx** [comment]
According to RFC2045, the standard does not want spaces here (http://tools.ietf.org/html/rfc2045#section-5.1), but I think it'll be a lot harder to convince everyone using a mua that inserts spaces here to switch to something else than just allowing the behaviour on this side.

**Comment by gauteh** [comment]
Ok, merged, thanks!

**Pull request merged**
